FROM mcr.microsoft.com/devcontainers/javascript-node:dev-22-bookworm

# Optional: install Eleventy globally (not strictly necessary, since you're using npx)
# RUN npm install -g @11ty/eleventy

WORKDIR /workspace
